### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by TimKraft**
I didn't find a better way to fix "Unexpected token..." issue while running ember server.

### CODE REVIEW

**Comment by lolmaus** [comment]
Please update your Node. Current version is `6.3.1`. You can use [nvm](https://github.com/creationix/nvm) to manage multiple Node versions effortlessly in case you have to deal with a legacy project that won't work on modern Node.

**Comment by lolmaus** [comment]
I'm available in the chat, in case you want to discus your plans to avoid going in the wrong direction and wasting effort.

This addon might miss functionality that you might require. In that case, let's discus it before you start coding.

**Comment by TimKraft** [comment]
Hi, @lolmaus. So, do we need to change node version for exam-sim-ember?

**Comment by lolmaus** [comment]
You need to install an up-to-date Node version on your computer.

I've relaxed the version requirement to `6` in the `.node-version` file (used by `.nvm`), both in `exam-sim-ember` and `ember-katex`.

**Pull request closed without merging**
